Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,19 +18,29 @@ jobs:
 #           POSTGRES_DB: circle_test
 #           POSTGRES_PASSWORD: ""
     steps:
-      - run:
-          name: Git config
-          command: |
-            mkdir -p ~/.ssh
-            touch ~/.ssh/known_hosts
-            if [ ! -n "$(grep "^github.com " "$HOME"/.ssh/known_hosts)" ]; then
-              ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
-            fi
+#       - run:
+#           name: Git config
+#           command: |
+#             mkdir -p ~/.ssh
+#             touch ~/.ssh/known_hosts
+#             if [ ! -n "$(grep "^github.com " "$HOME"/.ssh/known_hosts)" ]; then
+#               ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
+#             fi
 
-            git config --global url."ssh://git@github.com".insteadOf "https://github.com" ||:
-            git config --global gc.auto 0 ||:
-          shell: /usr/bin/env bash -eox pipefail -c
+#             git config --global url."ssh://git@github.com".insteadOf "https://github.com" ||:
+#             git config --global gc.auto 0 ||:
+#           shell: /usr/bin/env bash -eox pipefail -c
+      - run:
+          name: Dependency Audit
+          command: |
+            response_code=$(curl https://registry.yarnpkg.com/-/npm/v1/security/audits -s -o /dev/null -X POST -d {} -w '%{http_code}')
+            if [ $response_code = 200 ]; then
+              yarn audit --network-timeout=100000
+            else
+              echo -e "\e[41myarn audit server failed with status code $response_code. Skipping."
+              exit 0
+            fi
           
-      - run: git clone --branch $CIRCLE_BRANCH --single-branch --depth 1 $CIRCLE_REPOSITORY_URL .      
+#       - run: git clone --branch $CIRCLE_BRANCH --single-branch --depth 1 $CIRCLE_REPOSITORY_URL .      
 
       
