Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,22 +5,22 @@ jobs:
       - image: circleci/python:3.6-jessie-browsers
     steps:
 #       - checkout
-      - run: sudo ping cmsuat.canamins.com      
-#       - run: echo "hello world"
-#       - run: mkdir tests
-#       - run: cd tests && touch my_test_1.txt
-#       - run: echo "this is a test" > my_test_1.txt
-#       - store_artifacts:
-#           path: tests
-#       - run: wqr    
-#       - run:
-#           name: conditional step
-#           command: echo "conditional step"
-# #           when: on_fail # Uploads code coverage results, pass or fail
-          #
+      - run: echo "hello world"
+      - run: 
+          command: >
+            current_wait_time=0
 
+            if (( $current_wait_time > 1800 )); then
+              if [[ "true" == "true" ]]; then
+                echo "Proceeding with future steps";
+                current_wait_time=$(( current_wait_time + 60 ))
+                exit 0;
+              else
+                echo "Failing job by exiting forcefully";
+                exit 1;
+              fi
+            fi      
       
-
 workflows:
     version: 2.1
     build_and_push:
@@ -29,44 +29,4 @@ workflows:
 
 
 
-# version: 2.1
-
-# executors:
-#   machine-executor:
-#     machine: true
-#     environment:
-#       RUN_TESTS: foobar
-
-#   node:
-#     docker:
-#       - image: circleci/node
-
-    
-# jobs:
-#   build:
-#     parameters:
-#       my-executor:
-#         default: machine-executor
-#         type: string  
-#     executor: << parameters.my-executor >> 
-#     steps:
-#       - checkout
-#       - run: echo "hello world"
-
-# workflows:
-#     build_and_push:
-#       jobs:
-#         - build 
-#         - build: 
-#             my-executor: node    
-
-   
-# version: 2.1
-# jobs:
-#   build:
-#     docker:
-#       - image: image: circleci/python:3.6-jessie-browsers
-#     steps:
-#       - checkout
-#       - run: sudo ping cmsuat.canamins.com
 
